export const GenerateText = [
  'a chin-su bottle with a hole in the bottom',
  'a futuristic city floating above the clouds, with neon lights and flying cars',
  'an ancient dragon made of glowing crystals perched on a mountain peak',
  'a giant treehouse village suspended in the rainforest with waterfalls surrounding it',
  'a serene underwater utopia with glowing jellyfish and futuristic structures',
  'a steampunk-inspired robot bartender mixing drinks in a Victorian-style pub',
  'a magical library where books float and glow with mystical energy',
  'an astronaut relaxing on a hammock between two planets in outer space',
  'a mystical forest with glowing mushrooms and a crystal-clear river running through',
  'a sci-fi spaceship landing in the middle of an ancient Roman colosseum',
  'a vintage train station at sunset, with steam rising from an old locomotive',
  'a futuristic market where robots and humans trade exotic alien fruits',
  'a colossal sandcastle city on a beach, with intricate towers and bridges',
  'a cyberpunk street full of vibrant neon signs, futuristic cars, and bustling crowds',
  'a medieval knight playing chess with a dragon in a candlelit dungeon',
  'a lighthouse standing tall amidst a storm, with waves crashing dramatically',
  'a spaceship shaped like a giant fish swimming through space',
  'an enormous clock tower in the middle of a forest, overgrown with vines',
  'a garden where the flowers glow in different colors and levitate in midair',
  'a carnival on Mars with gravity-defying roller coasters and red dust clouds',
  'a floating island with waterfalls cascading into the clouds below',
  'a Viking ship sailing across a sea of stars instead of water',
  'a mountain made entirely of candy, with rivers of chocolate and gumdrop trees',
  'an enchanted mirror in an ancient temple that shows alternate realities',
  'a futuristic diner where robots serve food to both aliens and humans',
  'a city built inside a giant snow globe, complete with tiny cars and people',
  'a surreal desert with giant glowing cacti and a sky full of swirling colors',
  'an abandoned amusement park overtaken by nature, with vines and flowers blooming on roller coasters',
  'a grand ballroom underwater, with elegantly dressed sea creatures dancing',
  'a giant octopus wrapping its tentacles around a futuristic skyscraper',
  'a mystical floating whale that carries a forest on its back, swimming through the sky',
  'a glass bridge stretching over a massive canyon with a glowing river below',
  'a futuristic floating farm, where crops grow on levitating platforms in the sky',
  'an alien marketplace filled with bizarre creatures, strange foods, and holographic displays',
  'a futuristic sports arena where robots compete in a high-tech version of soccer',
  'a magical village hidden inside a giant tree, with fairy lights illuminating the paths',
  'a spaceship graveyard with rusted old ships, overgrown with alien plants',
  'a giant turtle swimming through space, with cities built on its back',
  'a colossal library inside a crystal cave, with glowing books and floating staircases',
  'a festival in a futuristic city, with people in glowing outfits and fireworks made of light',
  'a mechanical dragon flying over a steampunk city, with gears and steam powering everything',
  'a surreal cityscape with upside-down skyscrapers and floating islands in the sky',
  'a time traveler’s laboratory filled with clocks, gadgets, and portals to different eras',
  'a space station orbiting a gas giant, with colorful clouds and lightning storms below',
  'a castle built on the back of a giant sea creature swimming through a vast ocean',
  'a cozy winter village at night, with glowing lanterns and snow-covered rooftops',
  'an enormous tree with glowing leaves and wooden bridges connecting its branches',
  'a robot artist painting a beautiful landscape on a canvas in a futuristic art gallery',
  'a street vendor in a futuristic city selling robotic pets to passing customers',
  'a peaceful alien landscape with two suns in the sky and purple grass',
  'a post-apocalyptic world where nature has reclaimed the ruins of human civilization',
  'a giant glass dome city on the moon, with futuristic buildings and a view of Earth',
  'a surreal chessboard where the pieces are living creatures, moving on their own',
  'a futuristic underwater hotel, with glass walls showing the ocean life around it',
  'an enchanted forest where the trees have glowing symbols carved into their bark',
  'a futuristic concert where holographic performers float above the audience',
  'a robot chef in a high-tech kitchen preparing a gourmet meal for guests',
  'an ancient temple hidden deep within a glowing crystal cave',
  'a surreal dreamscape where gravity is inverted and waterfalls flow upward',
  'a futuristic train speeding through a landscape of neon forests and glowing rivers',
  'a floating castle made of clouds, with rainbow bridges connecting different towers',
  'an ancient ruin overtaken by alien plants glowing with bioluminescence',
  'a futuristic race where hovercrafts zoom through the streets of a glowing city',
  'a carnival parade in a cyberpunk city, with neon floats and futuristic costumes',
  'a sprawling cityscape where skyscrapers are connected by glass tubes for transportation',
  'a group of astronauts exploring a mysterious alien temple on a distant planet',
  'a massive tree in the middle of a desert, glowing with an ethereal light',
  'a futuristic zoo where holographic animals interact with visitors',
  'a robotic dragon guarding a treasure trove of glowing jewels in a futuristic cave',
  'a magical floating garden with flowers that bloom only under the light of a full moon',
  'a high-tech mountain resort where people ski on holographic snow',
  'a flying ship made of glass, sailing through a sea of stars',
  'a futuristic sports stadium where humans and robots compete in extreme sports',
  'a mystical island surrounded by a sea of clouds, with ancient temples hidden within',
  'an enormous sculpture carved into the side of a mountain, glowing with hidden lights',
  'a futuristic nightclub with dancers in glowing suits and holographic DJ booths',
  'a flying city made of golden structures, with airships and bridges connecting towers',
];
