import React, {useState} from 'react';
import { useNavigate } from 'react-router-dom';
import { preview } from '../assets';
import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';

const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });

  const [generatingText, setGeneratingText] = useState(true);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    // Call the API to generate the image
    // await generateImage(form);
    setLoading(false);
    navigate('/');
  }

  const handleChange = (e) => { 
    const { name, value } = e.target;
    setForm({ ...form, [name]: value });
  }

  const handleGenerateText = async () => {
    setGeneratingText(true);
    const prompt = await getRandomPrompt();
    setForm({ ...form, prompt });
    setGeneratingText(false);
  }

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">Create </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Create imaginative and visually stunning images generated by DALL-E AI and share them with the community</p>
      </div> 
      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            LabelName='Your name'
            type='text'
            name='name'
            placeholder='Enter your name'
            value={form.name}
            handleChange={handleChange}
            isGenerating={generatingText}
            handleGenerating={handleGenerateText}
          />

        </div>
      </form>
    </section>
  );
} 

export default CreatePost;