name: Deploy Server Application 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t duongha11/serveraigenerator -f server/Dockerfile .
      - name: Push Docker Image
        run: docker push duongha11/serveraigenerator:latest 

  deploy: 
    needs: build
    runs-on: self-hosted
    steps: 
      - name: pull image from docker hub
        run: docker pull duongha11/serveraigenerator:latest
      - name: run container
        run: docker run -d -p 4000:4000 --name server-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' duongha11/serveraigenerator:latest

